<?php
declare(strict_types=1);
$lang = (($_GET['lang'] ?? getenv('INVOQLY_LANG') ?: 'en') === 'ar') ? 'ar' : 'en';
$rtl = $lang === 'ar';
$t = static fn(string $en,string $ar): string => htmlspecialchars($rtl?$ar:$en,ENT_QUOTES,'UTF-8');
?>
<!doctype html><html lang="<?= $lang ?>" dir="<?= $rtl?'rtl':'ltr' ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $t('Workspace','مساحة العمل') ?> — Invoqly</title><style>
:root{--paper:#f3f2ec;--ink:#111713;--muted:#667069;--line:rgba(17,23,19,.14)}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 20% 10%,rgba(166,244,107,.38),transparent 30%),var(--paper);color:var(--ink);font-family:Inter,'Segoe UI',sans-serif}.card{width:min(620px,100%);padding:42px;border:1px solid var(--line);border-radius:30px;background:rgba(255,255,255,.7);box-shadow:0 30px 80px rgba(17,23,19,.08)}.brand{display:flex;align-items:center;gap:10px;font-size:20px;font-weight:800;color:inherit;text-decoration:none}.brand img{width:38px}h1{margin:48px 0 14px;font-family:Georgia,serif;font-size:clamp(2.6rem,8vw,4.8rem);line-height:.95}p{color:var(--muted);line-height:1.7}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:30px}.btn{position:relative;isolation:isolate;overflow:hidden;display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 22px;border:1px solid var(--ink);border-radius:999px;background:transparent;color:var(--ink);font-weight:750;cursor:pointer;text-decoration:none}.btn:before{content:"";position:absolute;inset:0;z-index:-1;background:var(--ink);transform:translateX(-102%);transition:transform .22s}.btn:hover{color:#fff}.btn:hover:before{transform:none}.btn.primary{background:var(--ink);color:#fff}.status{margin-top:18px;font-size:13px;color:var(--muted)}
</style></head><body><main class="card"><a class="brand" href="index.php?lang=<?= $lang ?>"><img src="assets/invoqly-mark.svg" alt=""><span><?= $t('Invoqly','إنفوكلي') ?></span></a><h1><?= $t('Your workspace is next.','مساحة عملك هي الخطوة التالية.') ?></h1><p><?= $t('Authentication is connected. The next build will add your invoice dashboard, clients and bilingual invoice editor.','تم ربط تسجيل الدخول. سيضيف الإصدار التالي لوحة الفواتير والعملاء ومحرر الفواتير ثنائي اللغة.') ?></p><div class="actions"><a class="btn primary" href="index.php?lang=<?= $lang ?>"><?= $t('Back to website','العودة للموقع') ?></a><button class="btn" id="signOut" type="button"><?= $t('Sign out','تسجيل الخروج') ?></button></div><div class="status" id="status"><?= $t('Checking your secure session…','جارٍ التحقق من جلستك الآمنة…') ?></div></main>
<script src="assets/supabase-config.js"></script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/dist/umd/supabase.min.js"></script><script>(async function(){var c=window.INVOQLY_CONFIG||{},s=document.getElementById('status'),b=document.getElementById('signOut');if(!c.supabaseUrl||!c.supabasePublishableKey||!window.supabase){s.textContent='<?= $t('Supabase configuration is still required.','لا يزال إعداد Supabase مطلوبًا.') ?>';b.disabled=true;return}var client=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey),result=await client.auth.getSession();if(!result.data.session){location.href='login.html';return}s.textContent='<?= $t('Signed in securely.','تم تسجيل الدخول بأمان.') ?>';b.addEventListener('click',async function(){await client.auth.signOut();location.href='login.html'})}());</script></body></html>
