<?php
declare(strict_types=1);
$lang = 'en';
$rtl = $lang === 'ar';
$t = static fn(string $en,string $ar): string => htmlspecialchars($rtl?$ar:$en,ENT_QUOTES,'UTF-8');
?>
<!doctype html><html lang="<?= $lang ?>" dir="<?= $rtl?'rtl':'ltr' ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $t('Workspace','مساحة العمل') ?> — <?= $t('Invoqly','إنفوكلي') ?></title><link rel="stylesheet" href="assets/workspace.css"></head><body>
<a class="skip" href="#content"><?= $t('Skip to content','انتقل إلى المحتوى') ?></a>
<aside class="sidebar" id="sidebar"><button class="subtle mobile-close" id="closeMenu" type="button"><?= $t('Close navigation ×','إغلاق القائمة ×') ?></button><a class="brand" href="#overview"><img src="assets/invoqly-mark.svg" alt=""><span><?= $t('Invoqly','إنفوكلي') ?><small><?= $t('YOUR INVOICING WORKSPACE','مساحة فواتيرك') ?></small></span></a><div class="business-label"><span class="business-initial" id="businessInitial">IQ</span><div><strong id="businessLabel"><?= $t('Your business','نشاطك التجاري') ?></strong><small><?= $t('Personal workspace','مساحة عمل شخصية') ?></small></div></div><nav aria-label="<?= $t('Workspace navigation','التنقل') ?>" id="navigation"></nav><div class="sidebar-bottom"><a href="#help"><?= $t('Help & getting started','المساعدة والبدء') ?></a><button id="collapse" class="subtle" type="button" aria-expanded="true"><?= $t('Collapse sidebar','طي القائمة') ?></button><button id="signOut" class="subtle" type="button"><?= $t('Sign out','تسجيل الخروج') ?></button></div></aside>
<div class="workspace"><header class="topbar"><div class="topbar-left"><button class="icon-button mobile-menu" id="menu" aria-label="<?= $t('Toggle navigation','إظهار القائمة') ?>" type="button">☰</button><span><?= $t('Workspace','مساحة العمل') ?> <span class="crumb">/</span> <strong id="breadcrumb"></strong></span></div><div class="topbar-actions"><button class="icon-button" id="theme" type="button" aria-label="<?= $t('Toggle dark mode','تغيير المظهر') ?>">◐</button><a class="avatar" id="avatar" href="#profile" aria-label="<?= $t('Your profile','ملفك الشخصي') ?>">IQ</a></div></header><main id="content" tabindex="-1"><div class="loading-state" role="status"><?= $t('Opening your workspace…','جارٍ فتح مساحة العمل…') ?></div></main><footer class="workspace-footer"><span>© <?= date('Y') ?> <?= $t('Invoqly','إنفوكلي') ?></span><div><a href="terms.php?lang=<?= $lang ?>"><?= $t('Terms','الشروط') ?></a><a href="privacy.php?lang=<?= $lang ?>"><?= $t('Privacy','الخصوصية') ?></a></div></footer></div><div id="toast" class="toast" role="status" aria-live="polite" hidden></div><script src="assets/supabase-config.js"></script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/dist/umd/supabase.min.js"></script><script src="assets/currencies.js"></script><script src="assets/workspace.js"></script></body></html>
