<?php
declare(strict_types=1);
$lang = (($_GET['lang'] ?? getenv('INVOQLY_LANG') ?: 'en') === 'ar') ? 'ar' : 'en';
$rtl = $lang === 'ar';
$t = static fn(string $en, string $ar): string => htmlspecialchars($rtl ? $ar : $en, ENT_QUOTES, 'UTF-8');
$sections = [
  ['1. Agreement and eligibility','١. الاتفاق والأهلية','These Terms form an agreement between you and Invoqly when you create an account, access the service or continue with Google. You must be legally able to enter a contract and, if acting for a business, authorized to accept these Terms for that business. If you do not agree, do not use the service.','تشكل هذه الشروط اتفاقًا بينك وبين إنفوكلي عند إنشاء حساب أو الوصول إلى الخدمة أو المتابعة باستخدام Google. يجب أن تكون مؤهلاً قانونيًا لإبرام عقد، وإذا كنت تتصرف نيابة عن نشاط تجاري فيجب أن تكون مخولاً بقبول هذه الشروط عنه. إذا لم توافق، فلا تستخدم الخدمة.'],
  ['2. The Invoqly service','٢. خدمة إنفوكلي','Invoqly is an early-stage platform for creating, translating, sending, organizing and tracking invoices and related client information. Features may include bilingual English and Arabic documents, multiple currencies, payment-status tracking and reminders. Some described features may be introduced gradually during the beta.','إنفوكلي منصة في مرحلة مبكرة لإنشاء الفواتير وترجمتها وإرسالها وتنظيمها ومتابعتها مع معلومات العملاء ذات الصلة. قد تشمل الميزات مستندات ثنائية اللغة وعملات متعددة وتتبع حالة الدفع والتذكيرات. قد تُطرح بعض الميزات تدريجيًا خلال النسخة التجريبية.'],
  ['3. Beta access and future plans','٣. الوصول التجريبي والخطط المستقبلية','The current beta is offered free of charge and without a payment card. We may change, test, limit, suspend or discontinue beta features as the product develops. We will clearly disclose any future prices, renewal terms and material plan limits before you become responsible for a charge. Participation in the beta does not guarantee permanent free access or the release of any feature.','تُقدم النسخة التجريبية الحالية مجانًا ودون بطاقة دفع. قد نغيّر الميزات التجريبية أو نختبرها أو نحدّها أو نعلقها أو نوقفها مع تطور المنتج. سنوضح بجلاء أي أسعار مستقبلية وشروط التجديد وحدود الخطط الجوهرية قبل تحملك أي رسوم. لا تضمن المشاركة وصولاً مجانيًا دائمًا أو إطلاق أي ميزة.'],
  ['4. Accounts and authentication','٤. الحسابات وتسجيل الدخول','You must provide accurate account details and keep them current. You are responsible for safeguarding your password, Google account and devices used to access Invoqly. Do not share an account in a way that defeats plan or security limits. Notify us promptly at hello@invoqly.ae if you suspect unauthorized access.','يجب تقديم بيانات حساب دقيقة وتحديثها. أنت مسؤول عن حماية كلمة المرور وحساب Google والأجهزة المستخدمة للوصول إلى إنفوكلي. لا تشارك الحساب بطريقة تتجاوز حدود الخطة أو الأمان. أبلغنا سريعًا عبر hello@invoqly.ae إذا اشتبهت بوصول غير مصرح به.'],
  ['5. Your content and licence to operate','٥. محتواك وترخيص التشغيل','You retain ownership of business details, client records, logos, invoice content and files you submit. You grant Invoqly a limited, non-exclusive licence to host, copy, process, format, translate and transmit that content only as needed to provide, secure and improve the service. You confirm that you have the rights and lawful basis needed to submit personal or business information about clients and team members.','تحتفظ بملكية بيانات النشاط وسجلات العملاء والشعارات ومحتوى الفواتير والملفات التي تقدمها. تمنح إنفوكلي ترخيصًا محدودًا وغير حصري لاستضافة المحتوى ونسخه ومعالجته وتنسيقه وترجمته ونقله فقط بالقدر اللازم لتقديم الخدمة وتأمينها وتحسينها. وتؤكد امتلاكك الحقوق والأساس القانوني اللازم لتقديم معلومات العملاء وأعضاء الفريق.'],
  ['6. Invoice, tax and legal responsibility','٦. مسؤولية الفواتير والضرائب والقانون','You are responsible for reviewing every invoice before sending it, including names, addresses, amounts, currencies, payment details, tax calculations, translations and required disclosures. You decide whether an invoice meets the laws, tax rules, accounting standards and retention requirements that apply to you and your client. Invoqly is software, not a law firm, tax adviser, accountant, payment processor or government filing service.','أنت مسؤول عن مراجعة كل فاتورة قبل إرسالها، بما يشمل الأسماء والعناوين والمبالغ والعملات وبيانات الدفع والحسابات الضريبية والترجمات والإفصاحات المطلوبة. وأنت من يحدد ما إذا كانت الفاتورة تستوفي القوانين والقواعد الضريبية والمعايير المحاسبية ومتطلبات الاحتفاظ المطبقة عليك وعلى عميلك. إنفوكلي برنامج وليست مكتب محاماة أو مستشارًا ضريبيًا أو محاسبًا أو معالج دفع أو خدمة تقديم حكومية.'],
  ['7. Acceptable use','٧. الاستخدام المقبول','You may not use Invoqly to commit fraud; issue deceptive or unlawful invoices; impersonate another person; violate sanctions, export controls or intellectual-property rights; distribute malware or spam; harass others; scrape the service; probe security; bypass access controls; overload infrastructure; or access accounts or data without authorization.','لا يجوز استخدام إنفوكلي للاحتيال أو إصدار فواتير مضللة أو غير قانونية أو انتحال شخصية الغير أو مخالفة العقوبات أو ضوابط التصدير أو حقوق الملكية الفكرية أو نشر البرمجيات الضارة أو الرسائل المزعجة أو مضايقة الآخرين أو استخراج بيانات الخدمة أو اختبار أمنها أو تجاوز ضوابط الوصول أو إرهاق البنية التحتية أو الوصول إلى حسابات أو بيانات دون تصريح.'],
  ['8. Third-party services','٨. خدمات الأطراف الثالثة','Invoqly relies on third parties such as Cloudflare, Supabase and Google authentication. Your use of those services may also be governed by their terms and privacy policies. We are not responsible for third-party outages, changes or acts outside our reasonable control, but we select providers with security and reliability in mind.','تعتمد إنفوكلي على أطراف ثالثة مثل Cloudflare وSupabase وتسجيل الدخول عبر Google. قد يخضع استخدامك لتلك الخدمات أيضًا لشروطها وسياسات الخصوصية الخاصة بها. لسنا مسؤولين عن انقطاعات الأطراف الثالثة أو تغييراتها أو أفعالها الخارجة عن سيطرتنا المعقولة، مع اختيار مزودين يراعون الأمان والموثوقية.'],
  ['9. Invoqly intellectual property','٩. ملكية إنفوكلي الفكرية','The service, software, design, brand, documentation and original content supplied by Invoqly are owned by Invoqly or its licensors and protected by applicable intellectual-property laws. These Terms give you a limited, revocable, non-transferable right to use the service for your internal business purposes. They do not transfer ownership of Invoqly technology or branding.','الخدمة والبرنامج والتصميم والعلامة والوثائق والمحتوى الأصلي المقدم من إنفوكلي مملوكة لإنفوكلي أو لمرخصيها ومحمية بقوانين الملكية الفكرية المعمول بها. تمنحك هذه الشروط حقًا محدودًا وقابلاً للإلغاء وغير قابل للتحويل لاستخدام الخدمة لأغراض نشاطك الداخلية، ولا تنقل ملكية تقنية إنفوكلي أو علامتها.'],
  ['10. Feedback','١٠. الملاحظات','If you voluntarily provide suggestions, designs or product feedback, you allow us to use them without restriction or payment to improve Invoqly. This does not give us ownership of your invoice content, confidential business data or trademarks.','إذا قدمت طوعًا اقتراحات أو تصاميم أو ملاحظات عن المنتج، فإنك تسمح لنا باستخدامها دون قيد أو مقابل لتحسين إنفوكلي. ولا يمنحنا ذلك ملكية محتوى فواتيرك أو بيانات نشاطك السرية أو علاماتك التجارية.'],
  ['11. Suspension and termination','١١. التعليق والإنهاء','You may stop using Invoqly at any time and may request account deletion. We may restrict or suspend access when reasonably necessary to protect users or the service, investigate misuse, comply with law, prevent harm or respond to a material breach. Where practical and lawful, we will provide notice and an opportunity to resolve the issue.','يمكنك التوقف عن استخدام إنفوكلي في أي وقت وطلب حذف الحساب. قد نقيّد الوصول أو نعلقه عند الضرورة المعقولة لحماية المستخدمين أو الخدمة أو التحقيق في إساءة الاستخدام أو الامتثال للقانون أو منع الضرر أو معالجة مخالفة جوهرية. وسنقدم إشعارًا وفرصة لمعالجة المشكلة متى كان ذلك عمليًا وقانونيًا.'],
  ['12. Availability and changes','١٢. التوفر والتغييرات','We aim to provide a reliable service but do not promise uninterrupted or error-free operation, permanent storage, or compatibility with every device or third-party system. Maintenance, testing, security events and provider outages may affect availability. Keep independent copies of records you are legally or operationally required to retain.','نسعى لتقديم خدمة موثوقة، لكننا لا نعد بتشغيل دون انقطاع أو أخطاء أو بتخزين دائم أو توافق مع كل جهاز أو نظام خارجي. قد تؤثر الصيانة والاختبارات والحوادث الأمنية وانقطاعات المزودين في التوفر. احتفظ بنسخ مستقلة من السجلات التي يلزمك قانونيًا أو تشغيليًا الاحتفاظ بها.'],
  ['13. Disclaimers','١٣. إخلاء المسؤولية','To the maximum extent permitted by law, the beta is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness for a particular purpose and non-infringement. Nothing in these Terms excludes rights or warranties that cannot lawfully be excluded.','في أقصى حدود يسمح بها القانون، تُقدم النسخة التجريبية «كما هي» و«حسب التوفر». نخلي مسؤوليتنا عن الضمانات الضمنية المتعلقة بالقابلية للتسويق والملاءمة لغرض معين وعدم التعدي. لا تستبعد هذه الشروط الحقوق أو الضمانات التي لا يجوز قانونًا استبعادها.'],
  ['14. Limitation of liability','١٤. تحديد المسؤولية','To the maximum extent permitted by law, Invoqly will not be liable for indirect, incidental, special, exemplary or consequential loss; lost profit, revenue, goodwill or data; tax penalties; payment disputes; or decisions made solely from generated or translated content. For a free beta, our aggregate liability relating to the service will not exceed USD 100, except where a different limit is required by law.','في أقصى حدود يسمح بها القانون، لا تتحمل إنفوكلي الخسائر غير المباشرة أو العرضية أو الخاصة أو التبعية أو فقدان الأرباح أو الإيرادات أو السمعة أو البيانات أو الغرامات الضريبية أو نزاعات الدفع أو القرارات المبنية فقط على محتوى مُنشأ أو مترجم. وفي النسخة التجريبية المجانية، لا تتجاوز مسؤوليتنا الإجمالية المتعلقة بالخدمة ١٠٠ دولار أمريكي، إلا إذا تطلب القانون حدًا مختلفًا.'],
  ['15. Governing rules and disputes','١٥. القواعد الحاكمة والنزاعات','These Terms are governed by the laws applicable to the Invoqly operator at the time a dispute arises, without overriding mandatory consumer protections that apply where you live. Before starting formal proceedings, both sides should try in good faith for 30 days to resolve the matter by contacting hello@invoqly.ae.','تخضع هذه الشروط للقوانين المطبقة على الجهة المشغلة لإنفوكلي وقت نشوء النزاع، دون تجاوز حماية المستهلك الإلزامية المطبقة في مكان إقامتك. وقبل بدء إجراءات رسمية، ينبغي للطرفين محاولة حل المسألة بحسن نية لمدة ٣٠ يومًا عبر التواصل مع hello@invoqly.ae.'],
  ['16. General terms and contact','١٦. أحكام عامة والتواصل','If part of these Terms is unenforceable, the remaining parts continue. A delay in enforcing a right is not a waiver. You may not transfer these Terms without our consent; we may transfer them as part of a financing, reorganization or sale of the business. We may update these Terms and will provide reasonable notice of material changes. Questions may be sent to hello@invoqly.ae.','إذا تعذر تنفيذ جزء من هذه الشروط، تستمر الأجزاء الأخرى. لا يعد التأخر في إنفاذ حق تنازلاً عنه. لا يجوز لك نقل هذه الشروط دون موافقتنا، وقد ننقلها ضمن تمويل أو إعادة تنظيم أو بيع للنشاط. قد نحدّث الشروط وسنقدم إشعارًا معقولاً بالتغييرات الجوهرية. يمكن إرسال الأسئلة إلى hello@invoqly.ae.'],
];
require __DIR__ . '/legal-view.php';
