begin;
insert into auth.users(id,email) values ('00000000-1111-4444-8888-111111111111','invoqly-workspace-test@example.invalid'),('00000000-2222-4444-8888-222222222222','invoqly-isolation-test@example.invalid');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-1111-4444-8888-111111111111',true);
do $test$
declare b uuid;c uuid;i uuid;n text;caught boolean:=false;j uuid;k uuid;
begin
 insert into public.businesses(name) values('Workspace transaction test') returning id into b;
 insert into public.clients(business_id,name) values(b,'Test client') returning id into c;
 i:=public.save_invoice_draft(null,b,c,current_date,current_date+7,'USD','en','note','bank','[{"description":"Design","quantity":2,"unit_price":50,"tax_rate":5}]');
 select invoice_number into n from public.invoices where id=i;
 if n<>'INV-000001' then raise exception 'Numbering failed';end if;
 if (select sum(line_subtotal+line_tax) from public.invoice_items where invoice_id=i)<>105 then raise exception 'Totals failed';end if;
 begin perform public.save_invoice_draft(i,b,c,current_date,current_date+7,'USD','en','','','[{"description":"","quantity":1,"unit_price":1}]');exception when others then caught:=true;end;
 if not caught or (select count(*) from public.invoice_items where invoice_id=i)<>1 then raise exception 'Atomic rollback failed';end if;
 update public.invoices set status='sent' where id=i;
 perform public.record_invoice_payment(i,25,now(),'cash','partial');
 if (select status from public.invoices where id=i)<>'partially_paid' then raise exception 'Partial payment failed';end if;
 caught:=false;begin perform public.record_invoice_payment(i,100,now(),'cash','overpayment');exception when others then caught:=true;end;
 if not caught then raise exception 'Overpayment accepted';end if;
 perform public.record_invoice_payment(i,80,now(),'bank_transfer','final');
 if (select status from public.invoices where id=i)<>'paid' then raise exception 'Paid status failed';end if;
 j:=public.save_invoice_draft(null,b,c,current_date,null,'JPY','en','','','[{"description":"Yen test","quantity":1,"unit_price":100.55,"tax_rate":0}]');
 if (select line_subtotal from public.invoice_items where invoice_id=j)<>101 then raise exception 'JPY precision failed';end if;
 update public.invoices set status='sent' where id=j;
 caught:=false;begin perform public.record_invoice_payment(j,1.5,now(),'cash','fractional yen');exception when others then caught:=true;end;
 if not caught then raise exception 'Fractional JPY payment accepted';end if;
 k:=public.save_invoice_draft(null,b,c,current_date,null,'KWD','en','','','[{"description":"Dinar test","quantity":1,"unit_price":1.234,"tax_rate":0}]');
 if (select line_subtotal from public.invoice_items where invoice_id=k)<>1.234 then raise exception 'KWD precision failed';end if;
 update public.invoices set status='sent' where id=k;
 perform public.record_invoice_payment(k,1.234,now(),'cash','three decimal payment');
 if (select amount from public.payments where invoice_id=k)<>1.234 then raise exception 'Payment precision lost';end if;
 perform set_config('request.jwt.claim.sub','00000000-2222-4444-8888-222222222222',true);
 if exists(select 1 from public.invoices where id=i) then raise exception 'Account isolation failed';end if;
 caught:=false;begin perform public.record_invoice_payment(j,1,now(),'cash','forbidden');exception when others then caught:=true;end;
 if not caught then raise exception 'Payment ownership failed';end if;
end;$test$;
select 'PASS: numbering, totals, atomic rollback, partial/full payments, overpayment prevention, currency precision and account isolation' as result;
rollback;
